---
title: "App Name Here"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: "https://github.com/cds490-top-fall20/air-quality"
runtime: shiny
---

```{r global, include=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(shiny))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(sf))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(leafpop))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(flexdashboard))
suppressPackageStartupMessages(library(RColorBrewer))

full_data <- read_rds("data/counties_mapping_data_simplified.rds") %>% 
  mutate(
    `Pollutant Grade` = case_when(
      `Pollutant Grade` == "DNC" ~ NA_character_,
      `Pollutant Grade` == "INC" ~ NA_character_,
      TRUE ~ `Pollutant Grade`,
    ),
    `Ozone Grade` = case_when(
      `Ozone Grade` == "DNC" ~ NA_character_,
      `Ozone Grade` == "INC" ~ NA_character_,
      TRUE ~ `Ozone Grade`,
    ),
    `Annual Pass/Fail` = case_when(
      `Annual Pass/Fail` == "DNC" ~ NA_character_,
      `Annual Pass/Fail` == "INC" ~ NA_character_,
      TRUE ~ `Annual Pass/Fail`,
    ),
    `Pollutant Grade` = as.factor(`Pollutant Grade`),
    `Ozone Grade` = as.factor(`Ozone Grade`),
    # `Annual Pass/Fail` = as.factor(`Annual Pass/Fail`),
    `Annual Pass/Fail` = factor(`Annual Pass/Fail`,c("PASS","FAIL"))
  )
metros <- read_rds("data/urban_areas_simplified.rds")
map_data <- full_data %>% 
      filter(
        state_name == "Virginia"
      )
```


Map
===========

Inputs {.sidebar}
-----------------------------------------------------------------------

### Customize

```{r}
selectInput("state", "Choose a state:",
      full_data$state_name,
      selected = "Virginia"
    )
```


```{r}
selectInput(
  "Grade", 
  "What grade would you like to View?", 
  choices=c("Pollutant Grade"="Pollutant Grade",
            "Ozone Grade"="Ozone Grade",      
            "Annual Pass/Fail"="Annual Pass/Fail"))

```



Row 1 {data-height=650}
-----------------------------------------------------------------------

### Map


```{r}
output$sotaMap <- renderLeaflet(
  {
    factpal <- colorFactor(c("forestgreen","gold","firebrick1"), levels = levels(full_data[[input$Grade]]),na.color = "grey")

    leaflet(map_data) %>% 
      setView(-77.8, 37.8, 7) %>%
      addProviderTiles("Esri.WorldGrayCanvas") %>%
      addMapPane("metro_areas", zIndex = 400) %>%
      addMapPane("pollution_counties", zIndex = 420) %>%
      addPolygons(
        data = metros,
        color = "black",
        fillColor = "light grey",
        group = "Metro Areas",
        options = pathOptions(pane = "metro_areas")
      ) %>%
      hideGroup("Metro Areas") %>%
      addPolygons(
        # data = shape,
        label = ~county_name,
        fillColor = ~ factpal(map_data[[input$Grade]]),
        layerId = ~GEOID,
        opacity = 1,
        weight = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.5,
        # bringToFront = TRUE,
        options = pathOptions(pane = "pollution_counties"),
        popup = paste(
          "County:", map_data$county_name,"<br>",
          input$Grade, ":", map_data[[input$Grade]] ,"<br>"
          ),
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE
          )
        ) %>% 
      addLegend(
        pal = factpal, 
        values = ~full_data[[input$Grade]], 
        opacity = 0.7, 
        title = NULL,
        position = "bottomright"
        ) %>%
      addLabelOnlyMarkers(
        lng = ~metros$long,
        lat = ~metros$lat,
        label = ~metros$name,
        labelOptions = labelOptions(noHide = T, direction = 'center', textOnly = T),
        group = "Metro Areas",
        options = pathOptions(pane = "metro_areas")
        ) %>%
      addLayersControl(
        overlayGroups = c("Metro Areas"),
        options = layersControlOptions(collapsed = FALSE)
      )
    }
  )
leafletOutput("sotaMap")
```


Row 2 {data-height=350}
-------


### County stats

```{r}
clicked_county <- reactive({
  # print(input$sotaMap_shape_click)
  if (is.null(input$sotaMap_shape_click$id) == FALSE){
    county_stats <- map_data %>%
      filter(GEOID == input$sotaMap_shape_click$id)
    return(HTML(
      "County information for:", county_stats$county_name,
      "<br>Median house price: $", county_stats$median_house_value,
      "<br>Median rent: $", county_stats$median_rent,
      "<br>% of People who commute in:", 
      round(100 * county_stats$`Number of workers from other counties who commute to work in the county` / county_stats$`Number of residents`),
      "<br>% of People who commute to other counties:", 
      round(100 * county_stats$`Number of resident workers who commute to work in other counties` / county_stats$`Number of residents`),
      "<br>% of People who commute within county:", 
      round(100 * county_stats$`Number of resident workers who commute within county` / county_stats$`Number of residents`)
      ))
  }
  return(HTML("<p>Click on a county to display more information</p>"))
})
renderUI(clicked_county())
```


<!-- Possible information to go here: -->

<!-- * county grades -->

<!-- * transportation emission statistics -->

<!-- * housing information -->

<!-- * commuting information -->

### Another box

Ideas for content:

* Glossary/definitions?
* About the dashboard/ about us?
* Another visualization?




Compare
========

Inputs {.sidebar}
-----------------------------------------------------------------------

### Pick two counties
```{r}

county_list <- full_data$GEOID

names(county_list) <- paste(full_data$county_name, full_data$state_name, sep = ", ")

```

```{r}
selectInput("county1", "Choose county 1:", county_list)
```

```{r}
selectInput("county2", "Choose county 2:",county_list)
```

Row 1
------------

### County 1

```{r}
renderValueBox({
  articles <- filter(full_data, GEOID == input$county1)
  value <- as.numeric(articles$transportation_pm2.5)
  valueBox(round(value, digits = 3), " Tons of pm 2.5 Pollution per day for county 1.",
           icon = "ion-fireball")
})
```

```{r}
# full_data %>%
#   filter(GEOID == input$county1) %>%
#   pluck(median_rent)
```


Row 2
------------

### County 2

```{r}
renderValueBox({
  articles <- filter(full_data, GEOID == input$county2)
  value <- as.numeric(articles$transportation_pm2.5)
  valueBox(round(value, digits = 3), " Tons of pm 2.5 Pollution per day for county 2.",
           icon = "ion-fireball")
})
```

Data
=====


Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("datatable_state", "Choose a state:",
      full_data$state_name
    )
```

## Row 1

### Data



```{r}
DT::renderDataTable({
  full_data %>%
    filter(state_name == input$datatable_state )%>%
    datatable()
})

```


About
======


